services:
  db:
    container_name: rus_trans_db
    image: postgres:17.6
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - rus_trans_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', '-c', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB' ]
      interval: 5s
      retries: 5
      timeout: 10s

  app:
    container_name: rus_trans_api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "${PORT_API}:${PORT_API}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/app/static
    env_file:
      - .env
    command: >
      sh -c 'uv run python3 manage.py collectstatic --noinput &&
             uv run python3 manage.py makemigrations --noinput &&
             uv run python3 manage.py migrate &&
             uv run python3 manage.py create_test_data &&
             uv run gunicorn config.wsgi:application --bind 0.0.0.0:${PORT_API} --workers 3 --timeout 60 --preload'

  nginx:
    image: chocolatefrappe/nginx-modules:1.29.1-acme
    container_name: rus_trans_nginx
    restart: unless-stopped
    ports:
      - "${PORT_NGINX}:${PORT_NGINX}"    # Для challenge и redirect
      - "443:443"  # HTTPS
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf  # Теперь полный conf, не default
      - ./static:/app/static
      - ./acme-cache:/var/cache/nginx  # Для state_path (создай ./acme-cache локально)

volumes:
  rus_trans_data:
#  certbot_conf:
#  certbot_www: