events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name mer1d1an.ru;

        # Отдаём challenge-файлы для certbot
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Проксируем API/Django
        location / {
            proxy_pass http://rus_trans_api:8000;  # замените 8000 на значение PORT_API из .env
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
