events {
    worker_connections 1024;
}

http {
    upstream django_app {
        server app:${PORT_API};  # Используй переменную из docker-compose
    }

    server {
        listen 80;
        server_name mered1an.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl http2;
        server_name mered1an.ru;

        ssl_certificate /etc/letsencrypt/live/mered1an.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mered1an.ru/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers EECDH+AESGCM:EECDH+CHACHA20;
        ssl_prefer_server_ciphers off;
        ssl_session_cache shared:le_nginx_SSL:10m;
        ssl_session_timeout 1d;

        location / {
            proxy_pass http://django_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /app/static/;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }
}
